theme: jekyll-theme-minimal

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

title: Bach in a Box
description: Bach in a Box
layout: default
logo: /assets/img/bach-in-a-box-logo.png
show_downloads: true
google_analytics: